### PR TITLE
ULX3S and mouse

### PR DESCRIPTION
**Pull request by emard**
I placed all my ULX3S support in one commit.
in the next commit I added mouse support which demonstrates
its usage by moving the crosshair pointer and it can change
trigger level by rotation of the mouse wheel.

I tried to be more cleaner this time to minimize interventions in
your code.

### CODE REVIEW

**Comment by emard** [comment]
thanx for the merge, some problems are still here
strange github slightly messed stuff
I will try to fix them to compile

**Comment by hdl4fpga** [comment]
Thanks for your contribution

**Comment by emard** [comment]
Thanks also to you for this great scope project
Here's another small pull request that should be fixing it
i compiled and it works both serial and mouse together
with daisy

can you send me some email to vordah@gmail.com
for exchanging postage addresses for ulx3s board

**Comment by hdl4fpga** [comment]
I've sent you the email

thanks

**Pull request merged**
