### PR TITLE
Master

### PR DESCRIPTION
**Pull request by hdl4fpga**

### CODE REVIEW

**Comment by sensarbani77** [comment]
Hello. I have been following your hdl4fpga page on github. I appreciate your work of excellence. I need your help in establishing the UI where you have shown the waveforms.  Actually, I downloaded the hdl4fpga file, implemented the scope.xpr in vivado, and could generate the control window, but facing difficulty in achieving this window shown in the video (UI that shows the waveforms). Could you help me?

**Comment by hdl4fpga** [comment]
Yes, sure, contact me at https://gitter.im/hdl4fpga/community. But the waveforms are not shown on the UI. They are generated by FPGA. You need to connect a Monitor to the FPGA as it is described here https://www.youtube.com/watch?v=2w7V4eRLnQE The UI only controls the scope

**Comment by sensarbani77** [comment]
Thanks for replying. I have connected my arty board in this way (image
attached). I dumped the scope.xpr bit file and did the ethernet
configuration described in your video
https://www.youtube.com/watch?v=HwHwV_HSOW0. What should I do now?

thanks & regards,

Dr. Sarbani Sen

**Comment by hdl4fpga** [comment]
Thank you for your patience. I've fixed the issue. Sure there are still
other issues.
arty  btn(0) now requests an IP address by dhcp.

If you don't mind, let's go on gitter.

Regards

Miguel Angel

**Comment by hdl4fpga** [comment]
Hi

Have already you tried it after have been fixed ?
I really appreciate the feedback.

Regards

Miguel Angel

**Comment by sensarbani77** [comment]
Thank you so much for your cooperation. Actually we were involved in sme
other work, so could not try. But as soon as we make the connections, we
will let you know. And of course, we may need your help as well. I will
update you. Thank you once again.


thanks & regards,

Dr. Sarbani Sen

**Comment by sensarbani77** [comment]
Hii. We are able make the VGA connection and display the wave forms in
monitor(attached photo). Thanks to you.Now tcp/ip part we have to do. Could
you help me in the procesa of acquiring data in master.dat file?

**Comment by hdl4fpga** [comment]
Sorry, data capture is work in progress and it is still not ready yet. The
only thing that can be done is to see waveforms on a
display.It might be ready in a couple of months. This is demo is for that
https://github.com/hdl4fpga/hdl4fpga/wiki/Demos, now I have to merge it

BTW I'm attaching an image explaining what button you have to push to
request an IP address in case you missed it
You don't need to configure a dhcp server if you don't want, the system is
still backward compatible that were described on the youtube channel's
videos  or even you can hard code a fixed IP address.

Regards

Miguel Angel
[image: Arty_top_600__09303.png]

**Pull request closed without merging**
